fix(c): rename duplicated endpoint_buffer variable
Compiling C tests fail due to a duplicated variable:

> [163/171] Linking C executable ockam/codec/tests/ockam_codec_tests
> FAILED: ockam/codec/tests/ockam_codec_tests
> : && /usr/lib64/ccache/gcc   ockam/codec/tests/CMakeFiles/ockam_codec_tests.dir/codec.c.o
>      ockam/codec/tests/CMakeFiles/ockam_codec_tests.dir/variable_length_encoded_u2le_test.c.o
>      ockam/codec/tests/CMakeFiles/ockam_codec_tests.dir/public_key_test.c.o
>      ockam/codec/tests/CMakeFiles/ockam_codec_tests.dir/endpoint_local_test.c.o
>      ockam/codec/tests/CMakeFiles/ockam_codec_tests.dir/endpoint_channel_test.c.o
>      ockam/codec/tests/CMakeFiles/ockam_codec_tests.dir/endpoint_test.c.o
>      ockam/codec/tests/CMakeFiles/ockam_codec_tests.dir/route_test.c.o
>      -o ockam/codec/tests/ockam_codec_tests  -lcmocka-static  ockam/log/libockam_log.a
>         ockam/codec/libockam_codec.a  ockam/log/libockam_log.a && :
> /usr/bin/ld: ockam/codec/tests/CMakeFiles/ockam_codec_tests.dir/endpoint_test.c.o:(.bss+0x0):
>              multiple definition of `encoded_buffer'; ockam/codec/tests/CMakeFiles/
>              ockam_codec_tests.dir/endpoint_channel_test.c.o:(.bss+0x10): first defined here
> collect2: error: ld returned 1 exit status
> [165/171] Linking C static library ockam/transport/libockam_transport.a
> ninja: build stopped: subcommand failed.

This is duplicated between endpoint_test.c and endpoint_channel_test.c.

Rename the former to address_buffer as it seems like the most correct
next-choice name for the variable.

This seems to be a result of compiling many tests into a single binary.

Signed-off-by: Alexander Scheel <alexander.m.scheel@gmail.com>